apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: echo-crt
spec:
  secretName: echo-crt
  dnsNames:
  - echo1.arthurbdiniz.com
  - echo2.arthurbdiniz.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - echo1.arthurbdiniz.com
      - echo2.arthurbdiniz.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer