apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: echo-crt
spec:
  secretName: echo-crt
  dnsNames:
  - echo.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - echo.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer