# define Traefik configuration
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"
    # Do not verify backend certificates (use https backends)
    #InsecureSkipVerify = true
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
    [acme]
      email = "arthurbdiniz@gmail.com"
      storage = "/etc/traefik/acme/acme.json"
      acmeLogging = true
      entryPoint = "https"
      onDemand = true
      onHostRule = true
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [acme.httpChallenge]
        entryPoint = "http"
      [[acme.domains]]
      main = "arthurbdiniz.com"
    [web]
      address = ":8080"
    [kubernetes]