# define Traefik configuration
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"
    # Do not verify backend certificates (use https backends)
    #InsecureSkipVerify = true
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
    [acme]
    email = "example@email.com"
    storage = "/etc/traefik/acme/acme.json"
    acmeLogging = true
    entryPoint = "https"
    onDemand = true
    onHostRule = true
    [acme.httpChallenge]
      entryPoint = "http"
    [[acme.domains]]
    main = "example.com"
    [api]
      dashboard = true
    [web]
      address = ":8080"
    [kubernetes]